version: '3.7'
services:

  shopper:
    container_name: shopper
    env_file: .env
    build:
      context: ./Shopper
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  admin:
    container_name: admin
    env_file: .env
    build:
      context: ./Admin
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  vendor_api:
    container_name: vendor_api
    env_file: .env
    build:
      context: ./VendorAPI
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3002:3002"

  vendor_app:
    container_name: vendor_app
    env_file: .env
    build:
      context: ./VendorApp
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3003:3003"

  microservice:
    container_name: microservice
    env_file: .env
    build:
      context: .
      dockerfile: Microservice.Dockerfile
    depends_on:
      - postgres
  
  postgres:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./AuthService/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./AuthService/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./ProductService/sql/schema.sql:/docker-entrypoint-initdb.d/4.schema.sql
      - ./ProductService/sql/data.sql:/docker-entrypoint-initdb.d/5.data.sql
      - ./OrderService/sql/schema.sql:/docker-entrypoint-initdb.d/6.schema.sql
      - ./OrderService/sql/data.sql:/docker-entrypoint-initdb.d/7.data.sql
