version: '3.7'
services:

  shopper:
    container_name: shopper
    image: luke121/mockazon:shopper
    env_file: .env
    build:
      context: ./Shopper
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  admin:
    container_name: admin
    image: luke121/mockazon:admin
    env_file: .env
    build:
      context: ./Admin
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  vendor_api:
    container_name: vendor_api
    image: luke121/mockazon:vendor_api
    env_file: .env
    build:
      context: ./VendorAPI
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3002:3002"

  vendor_app:
    container_name: vendor_app
    image: luke121/mockazon:vendor_app
    env_file: .env
    build:
      context: ./VendorApp
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3003:3003"

  microservice:
    container_name: microservice
    image: luke121/mockazon:microservice
    env_file: .env
    build:
      context: .
      dockerfile: Microservice.Dockerfile
    depends_on:
      - postgres
  
  postgres:
    container_name: database
    image: luke121/mockazon:database
    build: 
        context: .
        dockerfile: Postgres.Dockerfile
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: