-- Alfonso Data --
INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f0', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "Spigen", "name": "Rugged Armor Pro Designed for Google Pixel Watch 2/Pixel Watch Case with Band Protective Google Pixel Watch Band (2023/2022) - Black", "rating": "4 stars", "price": "19.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/61roM4NrZ1L._AC_SY200_.jpg", "properties": {"color": "red"}, "description":"Everyday scratch defense with flexible and shock-absorbent layer"}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f1', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "PEAK", "name": "High Top Mens Basketball Shoes Streetball Master Breathable Non Slip Outdoor Sneakers Cushioning Workout Shoes for Fitness", "rating": "4 stars", "price": "47.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/81lIMJt9GoL._AC_SY200_.jpg", "properties": {"color": "blue"}, "description":"SEAMLESS INTEGRATED WEAVING & HOT-MELT PROCESS: High-quality integrated weaving combined with hot-melt process to fully reduce the discomfort of the foot and provide comfortable wrapping and support. The outsole of the Streetball Master is thick and solid, with a deep traction pattern that will wear nicely outdoors."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f2', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "SEDETA", "name": "44\" File Cabinet, Filing Cabinet fits Legal/Letter Size, 2 Drawer File Cabinets for Home Office with Lock, Power Strip, 6 Storage Shelves, Rustic Brown", "rating": "4 stars", "price": "139.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/81Xz29z8mHL._AC_SY200_.jpg", "properties": {"color": "brown"}, "description":"The file cabinet has 2 file drawers with 1 lock for Legal, Letter, A4 sizes standard file, power strip for charging 4 devices at the same time, spacious desktop large enough for printers and scanners, 6 storage shelves, 4 hooks and 4 industrial casters. Filing cabinet that can be combined with any computer desk to form an L-shaped office area."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f3', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "ELSKER&HOME", "name": "11x17 Diploma Frames with Tassel Holder for 8.5x11 Certificate Document Shadow Box, Mahogany Frame, Degree Double Mat, Black with Gold Rim", "rating": "4 stars", "price": "52.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/81tlwBWzSFS._AC_SY200_.jpg", "properties": {"color": "brown"}, "description":"11x17 inch diploma frame with double mat design is ideal for 8.5x11 inch / 21.59x27.94 cm diploma, certificate, document, photos and more; Also includes a tassel holder to display your graduation tassel with your certificate, shadow box with removable glass front makes it easy to insert documents and tassel, protective gift box ensures safe arrival."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f4', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "TOZO", "name": "HT2 Hybrid Active Noise Cancelling Headphones, Wireless Over Ear Bluetooth Headphones, 60H Playtime, Hi-Res Audio Custom EQ via App Deep Bass Comfort Fit Ear Cups, for Home Office Travel", "rating": "4 stars", "price": "26.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/31IqbwNxI6L._SR215,215_.jpg", "properties": {"color": "blue"}, "description":"This resin pen holder is very heavy, which can avoid being knocked down by pet or kids, and is not easy to fall when moving."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f5', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "Google", "name": "Pixel Watch - Android Smartwatch with Fitbit Activity Tracking - Heart Rate Tracking Watch Polished Silver Stainless Steel case with Charcoal Active band - WiFi", "rating": "4 stars", "price": "179.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/61JACry6ngL._AC_SY200_.jpg", "properties": {"color": "blue"}, "description":"This resin pen holder is very heavy, which can avoid being knocked down by pet or kids, and is not easy to fall when moving."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f6', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "Alohappy", "name": "Queen Bed Frame with 4 Storage Drawers and Bookcase Headboard, LED Bed Frame with Outlets and USB Ports, Metal Platform Bed Queen Size, No Box Spring Needed, Easy Assembly, Vintage Brown", "rating": "4 stars", "price": "399.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/81sFk8sdFEL._AC_SY200_.jpg", "properties": {"color": "brown"}, "description":"Queen bed frame with 4 under bed storage drawers are perfect for organizing off-season clothes and quilts, and come with black pads to prevent items from falling and dust entering. They are easy to pull in and out and it adds a lot of storage space for your bedroom"}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f7', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "Comix", "name": "Mesh Pen Pencil Holder with Post It Note Holders Desk Organizer, 3 Compartment Wire Desktop Pen Pencil Cup Caddy Office Supplies Accessories for Home Office School, Black", "rating": "4 stars", "price": "19.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/6131ZrfQgzL._AC_SY200_.jpg", "properties": {"color": "black"}, "description":"Comix desk organizer perfect choice for office and school, can keep your desk clean and tidy and your supplies organized."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f8', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "Amosanli", "name": "Knight Pen Holder Desk Organizers and Accessories Desk Decor Resin Pen Holder as Gift with a Cool Pen for Office and Home (Blue)", "rating": "4 stars", "price": "26.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/51JePhowjrL._AC_SR160,160_.jpg", "properties": {"color": "blue"}, "description":"This resin pen holder is very heavy, which can avoid being knocked down by pet or kids, and is not easy to fall when moving."}', TRUE);

INSERT INTO product(id, vendor_id, data, active) VALUES ('a1c689b1-b7a7-4100-8b2d-309908b444f9', '89f5cbfb-40a9-470d-ac8f-99e0416c6234', '{"brand": "SEDETA", "name": "L Shaped Computer Desk, Reversible Corner Desk with Power Outlet and Pegboard, Computer Desk with Led Lights, Keyboard Tray, Headphone Hook and Storage Shelves, Rustic Brown", "rating": "4 stars", "price": "179.99", "deliveryDate": "2020-01-01", "image": "https://m.media-amazon.com/images/I/81f19o0J6mL._AC_SY200_.jpg", "properties": {"color": "blue"}, "description":"This resin pen holder is very heavy, which can avoid being knocked down by pet or kids, and is not easy to fall when moving."}', TRUE);

-- Hunter Data --
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Eiichiro Oda", "name":"One Piece: East Blue 1-2-3", "price":"11.99", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/913RKmkEKNL._SY466_.jpg", "description":"Join Monkey D. Luffy and his swashbuckling crew in their search for the ultimate treasure, the One Piece. As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally ate the Gum-Gum Fruit, an enchanted Devil Fruit that gave him the ability to stretch like rubber. Its only drawback? He’ll never be able to swim again—a serious handicap for an aspiring sea dog! Years later, Luffy sets off on his quest to find the “One Piece,” said to be the greatest treasure in the world…"}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Bestylez Store", "name":"Black Cat Are You Pooping Funny Tin Signs Bathroom Wall Decor 8 x 12 Inch (918)", "price":"9.99", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/61UCvqpjOFL._AC_SY879_.jpg", "description":"Four Pre-drilled holes in the rounded corners for easy hanging or mounted on every surface, including walls, door, fence, poles and gates. Use with double-sided foam tape,command strips, jute rope or nails."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Ryan Gosling, Emma Stone (Actor), Damien Chazelle (Director)", "name":"La La Land [Blu-ray + DVD + Digital HD]", "price":"8.99", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/9101ZDVT9hL._SY445_.jpg", "description":"(Piano/Vocal/Guitar Songbook). Written and directed by Damien Chazelle, La La Land tells the story of Mia Emma Stone , an aspiring actress, and Sebastian Ryan Gosling , a dedicated jazz musician, who are struggling to make ends meet in a city known for crushing hopes and breaking hearts. Set in modern day Los Angeles, this original musical about everyday life explores the joy and pain of pursuing your dreams. Our matching folio features 10 piano/vocal/guitar arrangements from the award-winning soundtrack featuring original songs by Justin Hurwitz with lyrics by Benj Pasek and Justin Paul."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Ryan Gosling, Emma Stone (Actor), Damien Chazelle (Director)", "name":"BOSSIN 36 Electric Fireplace with Mantel, 23 inch Electric Fireplace Insert, TV Stand Freestanding Heater with Remote Control Timer LED Flame for Living Room Bedroom,Faux Stone Gray", "price":"279.99", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/81c17VzMmBL._AC_SX679_.jpg", "description":"【Realistic Flame Effect】: This fireplace can be used with or without heat and features 3D realistic flame effects, which is the perfect addition to your living room or dining area. 12 flame colors includes the upgraded 3 classic flame colors (red orange and blue),5 flame speeds & 5 flame brightness and 4 carbon fire colors option. The magnificent effect can be operated with or without heat ,giving your room a dreamlike ambiance."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Natures Path Store", "name":"Natures Path Organic Heritage Flakes Cereal, 33.5 Ounce, Non-GMO, 6 Ancient Grains, Low Sugar, High Fiber, 5g Plant Based Protein", "price":"7.59", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/81HEa1OO20L._SY741_.jpg", "description":"Best cereal ever made (real)"}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Donner Store", "name": "Donner DDP-100 88-Key Weighted Action Digital Piano for Beginner Bundle with Piano Keyboard Stand, Power Adapter, Triple Pedals, MP3 Function, USB-MIDI, 2 Headphone Jacks Black", "price":"529.99", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/71IVOVwaynL._AC_SX466_.jpg", "description":"Authentic Key Feel: Experience the precision of an 88-key fully-weighted action digital piano. Designed to replicate the genuine touch of traditional pianos, it captures every nuance for an enhanced playing experience."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Nature Made Store", "name":"Nature Made Melatonin 10mg Maximum Strength Tablets, 100% Drug Free Sleep Aid for Adults, 70 Count, 70 Day Supply", "price":"8.83", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/714zV0QoK7L._AC_SX679_.jpg", "description":"Maximum strength(1) sleep support supplement: Contains one 70 count bottle of Nature Made Melatonin 10 mg Maximum Strength(1) Tablets for a 70-day supply"}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"MiiCoffee Store", "name":"DF54 Single Dose Coffee Grinder (Black)", "price":"229", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/61rFq1NOoUL._AC_SX679_.jpg", "description":"【54mm Flat Burrs】Custom made 54mm stainless steel flat burrs.【Plasma Generator AKA Ionizer】Plasma Generator inside exit chute reduces static.【Single Dose & Zero Retention】True Zero Retention <0.1 gram. Even without bellow this grinder reaches almost zero retention. Use blow-out funnel with lid to completely empty the dead space."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Thomas H. Cormen", "name":"Introduction to Algorithms, fourth edition 4th Edition", "price":"67.97", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/61Mw06x2XcL._SY466_.jpg", "description":"Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. It covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers, with self-contained chapters and algorithms in pseudocode. Since the publication of the first edition, Introduction to Algorithms has become the leading algorithms text in universities worldwide as well as the standard reference for professionals. This fourth edition has been updated throughout."}', false);
INSERT INTO product (vendor_id, data, active) VALUES ('4f061f79-e0e8-48ff-a2ac-0a56a8ad5f0e', '{"brand":"Nongshim Store", "name":"Nongshim Gourmet Spicy Shin Instant Ramen Noodle, 20 Pack, Chunky Vegetables, Premium Microwaveable Ramen Soup Mix, Savory & Rich", "price":"34.30", "deliveryDate":"2024-04-07T07:00:29Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/813ZQHzytLL._SX679_.jpg", "description":"Nongshim Shin Ramyun is a classic, customizable ramyun to your preference by adding ingredients you think are the best fit for you. This is a dish that’s there for you any time of day or night."}', false);

-- Eisha Data --
insert into product (vendor_id, data, active) values ('78b9467a-8029-4c1f-afd9-ea56932c3f45', '{"brand":"Corelle Livingware", "name":"11-Ounce Stoneware Mug, Cobalt", "price":"15.00", "deliveryDate":"2024-02-29T21:58:56Z", "rating":"4 stars", "image":"https://m.media-amazon.com/images/I/41Ub370LqGL._AC_.jpg", "description":"Dishwasher safe for long lasting patterns"}', true);
insert into product (vendor_id, data, active) values ('78b9467a-8029-4c1f-afd9-ea56932c3f45', '{"brand":"STANLEY Store", "name":"Stanley Quencher H2.0 FlowState Stainless Steel Vacuum Insulated Tumbler", "price":"55.00", "deliveryDate":"2024-02-29T21:58:56Z", "rating":"5 stars", "image":"https://m.media-amazon.com/images/I/51glBADjrpL._AC_SL1500_.jpg", "description":"The H2.0 FlowState tumbler keeps you refreshed with fewer refills. Double wall vacuum insulation means drinks stay cold, iced or hot for hours. Choose between our 14oz, 20oz, 30oz,40oz and 64oz options depending on your hydration needs."}', true);
insert into product (vendor_id, data, active) values ('78b9467a-8029-4c1f-afd9-ea56932c3f45', '{"brand":"AXE", "name":"AXE Fine Fragrance Collection Premium Deodorant Body Spray for Men", "price":"31.00", "deliveryDate":"2024-02-29T21:58:56Z", "rating":"1 star", "image":"https://m.media-amazon.com/images/I/81O6H6PzTbL._SL1500_.jpg", "description":"Smell finer than the finest fragrances with the new variety pack from the AXE Fine Fragrance Collection."}', true);
insert into product (vendor_id, data, active) values ('78b9467a-8029-4c1f-afd9-ea56932c3f45', '{"brand":"Jugbow", "name":"Dog Shock Collar - 4200FT Dog Training Collar with Remote", "price":"1111.00", "deliveryDate":"2024-02-29T21:58:56Z", "rating":"2 star", "image":"https://m.media-amazon.com/images/I/71lCDyjEBSL.__AC_SX300_SY300_QL70_FMwebp_.jpg", "description":"Our dog shock collar features 4 humane training modes"}', true);
insert into product (vendor_id, data, active) values ('78b9467a-8029-4c1f-afd9-ea56932c3f45', '{"brand":"Instant Vortex Plus", "name":"Instant Vortex Plus 6QT XL Air Fryer, 6-in-1", "price":"321.00", "deliveryDate":"2024-02-29T21:58:56Z", "rating":"2 star", "image":"https://m.media-amazon.com/images/I/71cn-i+GCZL._AC_SL1500_.jpg", "description":"Air fry, broil, roast, dehydrate, bake and reheat"}', true);