DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS vendor CASCADE;
CREATE TABLE product(id UUID UNIQUE PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id UUID REFERENCES vendor(id), data jsonb, active BOOLEAN DEFAULT TRUE);