name: Mockazon CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  MASTER_SECRET: ${{ secrets.MASTER_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      # Lints and FE & BE tests
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run installs
      - name: Install prettier for formatting
        run: npm install -g prettier
      - run: npm run lints
      - run: npm run docker-up
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
      - run: npm run tests
      - run: npm run docker-down

      # E2E tests with containerized version 
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
      - name: Build files for container
        run: npm run builds
      - name: Spin up container
        run: docker-compose up -d --build
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
      - name: Run e2e tests
        run: npm run test-e2es