name: Connection Test

on:
  workflow_dispatch:

env:
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  MASTER_SECRET: ${{ secrets.MASTER_SECRET }}
  MICROSERVICE_URL: ${{ vars.MICROSERVICE_URL }}
  ENVIRONMENT: production
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Show if private key loads
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | grep "PRIVATE KEY"

      - uses: actions/checkout@v4
      - name: Copy docker compose
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose-production.yml"
          target: "/root"

      - name: Pull and run Docker image on the remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker compose -f /root/docker-compose-production.yml pull
            docker compose -f /root/docker-compose-production.yml down
            docker compose -f /root/docker-compose-production.yml up -d
            docker system prune -a -f --volumes
      - name: Wait for 20 seconds
        run: sleep 20

